### ISSUE TITLE
error generating banners files

### ISSUE THREAD

**Issue by nclsjstnn** [julesce/refinerycms-banners#2]
when i run "rails generate refinerycms_banners" i get this:

```
/Users/nicolasjustiniano/.rvm/gems/ruby-1.9.3-p0/gems/bundler-1.2.0.rc/lib/bundler/runtime.rb:74:in `require': cannot load such file -- refinerycms/banners (LoadError)
    from /Users/nicolasjustiniano/.rvm/gems/ruby-1.9.3-p0/gems/bundler-1.2.0.rc/lib/bundler/runtime.rb:74:in `rescue in block in require'
    from /Users/nicolasjustiniano/.rvm/gems/ruby-1.9.3-p0/gems/bundler-1.2.0.rc/lib/bundler/runtime.rb:62:in `block in require'
    from /Users/nicolasjustiniano/.rvm/gems/ruby-1.9.3-p0/gems/bundler-1.2.0.rc/lib/bundler/runtime.rb:55:in `each'
    from /Users/nicolasjustiniano/.rvm/gems/ruby-1.9.3-p0/gems/bundler-1.2.0.rc/lib/bundler/runtime.rb:55:in `require'
    from /Users/nicolasjustiniano/.rvm/gems/ruby-1.9.3-p0/gems/bundler-1.2.0.rc/lib/bundler.rb:128:in `require'
    from /Users/nicolasjustiniano/Sites/nanostern/config/application.rb:13:in `<top (required)>'
    from /Users/nicolasjustiniano/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/commands.rb:24:in `require'
    from /Users/nicolasjustiniano/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/commands.rb:24:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

this gems i have on that

Using refinerycms-core (2.0.8) 
Using refinerycms-authentication (2.0.8) 
Using refinerycms-dashboard (2.0.8) 
Using refinerycms-images (2.0.8) 
Using seo_meta (1.3.0) 
Using refinerycms-pages (2.0.8) 
Using refinerycms-resources (2.0.8) 
Using refinerycms (2.0.8) 
Using refinerycms-albums (1.0) from source at vendor/extensions 
Using refinerycms-banners (1.0) from git://github.com/julesce/refinerycms-banners.git (at master) 
Using refinerycms-settings (2.0.2) 
Using refinerycms-blog (2.0.4) 
Using routing-filter (0.3.1) 
Using refinerycms-i18n (2.0.2) 
Using refinerycms-page-images (2.0.1) 
Using refinerycms-search (2.0.0) from git://github.com/resolve/refinerycms-search.git (at 2-0-stable) 
Using refinerycms-tourdates (1.0) from source at vendor/extensions

**Comment by julesce** [comment]
Ah, this is the 1.0 version of the gem, which works with RefineryCMS 1.0.x.

You'll want to use the new gem, which is written for RefineryCMS 2.0.x:

https://github.com/julesce/refinerycms-pc_banners

I'll make a note to update the readme to point to the newer gem - thanks for pointing this out!
